### ISSUE TITLE
something about training

### ISSUE THREAD

**Issue by IRIS00123** [KaihuaTang/VQA2.0-Recent-Approachs-2018.pytorch#5]
您好，在GitHub上看到了您对近年来VQA模型复现的Git项目，非常感兴趣。我是一名对VQA感兴趣的在读研究生，有个问题想请教一下，在训练过程中，dataloader部分，question和answer的索引和编码占用了大约两至三分钟的时间，导致训练一个epoch需要大量的时间，训练效率低。您是怎么解决这个问题的呢？有什么建议吗？万分感谢！[机智]

**Comment by KaihuaTang** [comment]
应该是服务器内存不够大，所以卡在IO上了
